### ISSUE TITLE
请教一下装在TamperMonkey里了，怎么使用呢？

### ISSUE THREAD

**Issue by barbasting** [yujianke100/vits-simple-api-for-SillyTavern#1]
大佬你好，下载了你的插件并安装在了TamperMonkey，可是在用SillyTavern对话是没有找到那个按钮呀，新手小白求指导，感谢！

**Comment by yujianke100** [comment]
因为每个人的酒馆域名都不一样，要自己去代码里面改一下：
![image](https://github.com/yujianke100/vits-simple-api-for-SillyTavern/assets/35999482/8c635a1f-34da-45a5-809e-abb956734997)

把自己的酒馆地址输进去保存，刷新酒馆，成功的话能看到脚本在酒馆页面被激活：

![image](https://github.com/yujianke100/vits-simple-api-for-SillyTavern/assets/35999482/53de7c04-3017-4009-b612-087c064a160f)

对话框右上角看到按钮：

![image](https://github.com/yujianke100/vits-simple-api-for-SillyTavern/assets/35999482/7b598a1e-0de2-48eb-bb14-bebd8e53e505)

**Comment by yujianke100** [comment]
api也别忘记根据你的情况修改：

![image](https://github.com/yujianke100/vits-simple-api-for-SillyTavern/assets/35999482/8dabc23e-08c8-48f9-bdb1-950e603ca180)

**Comment by barbasting** [comment]
感谢感谢，明白了，问没有可能配置到扩展选项卡里的TTS下拉菜单里？不知道好操作吗？再次感谢解答

**Comment by yujianke100** [comment]
> 感谢感谢，明白了，问没有可能配置到扩展选项卡里的TTS下拉菜单里？不知道好操作吗？再次感谢解答

本身插件就不是很完善，不能提取引号内容读什么的，会去用的多折腾两行而已，不多做别的了。等官方支持吧

**Comment by barbasting** [comment]
好的，我先体验着，然后等官方吧。
